### ISSUE TITLE
data stewardship at NLeSC

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/ldm-sig#17]
[Training for data Stewards.](https://openworking.wordpress.com/2017/09/18/training-for-data-stewards/)

**Comment by c-martinez** [comment]
Small summary:

In principle, [the external course](https://datasupport.researchdata.nl/en/about-the-course/three-ways/) for data management seems like a good starting point -- I would expect the course not to be anything new to us.

Course can be done online or with in-person sessions. Next round of in-person courses is in October 2018. Estimate time required for the course is 50 hours.

My suggestion: one or two persons do the online course BEFORE OCTOBER and report back to data-sig. If he/she/they find the course useful, perhaps more people can do the online or in-person version.

**Comment by romulogoncalves** [comment]
A document from 2013 about data stewardship at NLeSC:
https://www.esciencecenter.nl/img/pressroom/DataStewardship_Final.pdf

**Comment by MartineDeVos** [comment]
@bpmweel 
Hi Berend, you already wrote a data management plan for a H2020 project. Could you please share the plan with us? Do you have tips or tricks for writing a data management plan?
