### ISSUE TITLE
UDF not working on Fedora

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/ldm-sig#2]
Perhaps it is my local version which is out of date, would be nice to make it work on Fedora :-)

**Comment by romulogoncalves** [comment]
Let us know the Fedora version so we can create a VM with the same version and test it.

**Comment by c-martinez** [comment]
fc23

**Comment by romulogoncalves** [comment]
Solved by
https://github.com/NLeSC/ldm-sig/commit/3555a14ac4b25f626069f4c8ffb92527bbfdab68
