### ISSUE TITLE
Data Management plan

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/ldm-sig#20]
Elaboration of data management plan. It should use data storage and preservation guidelines.

**Comment by romulogoncalves** [comment]
It was suggested that we have a workshop, kick start data management plan writing. Such workshop is supervised by the data-sig. Like this we would make sure they have similar quality and we help each other.

**Comment by c-martinez** [comment]
I believe @bpmweel had a data management plan from a proposal he was involved in? Maybe he can share it with us?

**Comment by romulogoncalves** [comment]
The data management plan for NLeSC calls will be elaborated by Frank Sienstra and the Tech Lead in Data Handling.

**Comment by c-martinez** [comment]
https://dmponline.dcc.ac.uk/ is also becoming popular. and @bpmweel has some experience with it -- he will share his experience on the next data-sig.

**Comment by c-martinez** [comment]
Adding first version of some text to the [guide](https://github.com/NLeSC/guide/pull/165).
