### ISSUE TITLE
Request to participate in NWA proposal on nano publications

### ISSUE THREAD

**Issue by ridderl** [NLeSC/ldm-sig#21]
Project idea on Semanic Publishing by Tobias Kuhn and Michel Dumontier:

# Motivation
Software has boosted scientific productivity, but we cannot use software to reliably interpret or aggregate the resulting scientific findings, because they are published in narrative articles optimized for humans and not for algorithms. This project will make a first step to solve this problem by using recent technologies to build a flexible framework for intuitive web interfaces for scientists to directly publish their findings in a formal computer-interpretable format.

# Project Description
This project will use the nanopublication technology to develop and test a framework for enabling quick and easy publishing of formal snippets of scientific results, which we call "nanoblogging", and will apply and evaluate it for two chosen use cases.

**Comment by ridderl** [comment]
[sempub-ideas.pdf](https://github.com/NLeSC/data-sig/files/2188420/sempub-ideas.pdf)

**Comment by c-martinez** [comment]
Good to know -- thanks! Let us know if you need help! Open new issue if you need input / help :-)
