### ISSUE TITLE
GeoSpatial Data Handling at NLeSC, an overview.

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/ldm-sig#22]
Data-SIG is trying to create an overview of standard data formats, technology and expertise for GeoSpatial Data Handling at NLeSC. 

Through comments, we invite our colleagues to report on type of GeoSpatial data sets they have worked on, such as Vector, Raster, PointCloud, etc, but also which tools they have used to manage and process them, and if possible on which project. The latter is not relevant, but welcomed.

**Comment by goord** [comment]
Do climate and weather data qualify as geospatial?

**Comment by c-martinez** [comment]
Sure -- so we would really like to hear your input.

**Comment by goord** [comment]
The usual suspects:
- [netCDF](https://www.unidata.ucar.edu/software/netcdf/) the file format for gridded data, plus file API's in various languages
- [CDO](https://code.mpimet.mpg.de/projects/cdo/): command-line tools for processing netcdf/grib files
- [NCO](http://nco.sourceforge.net/): more command-line tools for processing netcdf/grib files
- [eccodes](https://confluence.ecmwf.int/display/ECC/ecCodes+Home): API for processing GRIB files containing time slices of gridded data (a la netcdf but different, older)
- [iris](https://scitools.org.uk/iris/docs/latest/): python API for for processing netcdf/grib, quite new

**Comment by jiskattema** [comment]
for me:
* netCDF4
* CDO
* NCO
* python-netcdf4
* PROJ4
* shapely / fiona
* gdal
* PostgreSQL + PostGIS

**Comment by jiskattema** [comment]
and datasets:
* CBS's buurt en wijk
* kadaster: top10nl etc.
* AHN2 etc.
* gridded data containing RGBI fotos of NL at meter (?) resolution as an external dataset to PostGIS
* playing around with shapefiles

**Comment by sverhoeven** [comment]
A subset of https://github.com/sshuair/awesome-gis and https://github.com/sacridini/Awesome-Geospatial

**Comment by LourensVeen** [comment]
For me, with some overlap with the above, (and some of this is a bit stale, but it's stuff I've used):
- PostgreSQL/PostGIS
- GeoServer
- GDAL
- GeographicLib
- libTiff/libGeotiff
- QGIS
- Python geojson package

**Comment by elboyran** [comment]
For DynaSlum, I've worked with:

1. Data

- Raster (geotiff)

- Vector (shape files)

2. Tools & libraries

- QGIS

- shapely + fiona

- gdal

The PointCloud hands-on experience - only during  the eEcoLiDAR team sprint

**Comment by nielsdrost** [comment]
Perhaps also good to mention OSGeo (https://www.osgeo.org/), an organisation supporting a lot of the tools and libraries mentioned above.

Also, there is a suite of standards (WPS, WMS, WCS, ...) that are good to at least know about, most of them managed by OGC (http://www.opengeospatial.org/)

**Comment by nielsdrost** [comment]
Note that we once (in 2016) make a small effort to collection info on GeoSpatial data and software already. See the result here:

https://nlesc.gitbooks.io/geospatial-handbook/content/

**Comment by romulogoncalves** [comment]
@nielsdrost that's really cool news and a great starting point. Somehow I was not aware of it.
We were also looking for a place where to publish this information, this might a nice one.

Thanks for sharing.

**Comment by nielsdrost** [comment]
@romulogoncalves Yes, we could have announced it better ;-)

Perhaps it would be good to also involve the Geo office365 group at NLeSC? It's not quite a SIG, but we though about making it an official one a few times now. :-)

**Comment by bouweandela** [comment]
In addition to the lists above: [rasterio](https://github.com/mapbox/rasterio) is a more Python friendly package offering GDAL functionality.

**Comment by c-martinez** [comment]
This issue is quite old by now. I will close it, but please open it again if there is something to share (for example lessons learned) with the SIG on this topic.
