### ISSUE TITLE
Data formats and databases for SPOT

### ISSUE THREAD

**Issue by fdiblen** [NLeSC/ldm-sig#23]
I am planning to make some changes in SPOT in order to support most of the data formats and databases. I need an overview of the data types used in our projects.

The ones I can think of are:

data formats:
CSV
json
geojson
npy*
hdf5*
netcdf*
xml*
xls

databases:
Postresql
SQLite
MySQL?
MongoDB?
Redis?
CouchDB?
HBase?
Hive?

?:  not sure if we really use it in any projects
*:  not sure if we can support it easily

**Comment by arnikz** [comment]
The current list could be extended with:
1. RDF-based serializations (e.g. [Turtle](https://www.w3.org/TR/turtle/), sorry, not Python) or [JSON-LD](https://json-ld.org/)
2. Virtuoso RDBMS/RDF Store

However, one needs to know the schema to subset data and/or enable meaningful data import into SPOT, I think.

**Comment by egpbos** [comment]
ElasticSearch / Solr / Lucene

**Comment by fdiblen** [comment]
@arnikz @egpbos it would be nice if you could name the projects using these databases.

**Comment by egpbos** [comment]
I've used ES in the pidimehs project for analyzing newspaper texts.

**Comment by arnikz** [comment]
I've used Virtuoso in the ODEX4all (completed), candYgene, EOSCpilot-LOFAR and Googling The Cancer Genome projects. In addition, we use SQLite and Solr in candYgene.

**Comment by romulogoncalves** [comment]
@fdiblen would it be ok if you join the next DataSIG and share with us what is your plan? Like letting us know if data formats and Database management systems you will support?

**Comment by fdiblen** [comment]
@romulogoncalves
Sure. It would be nice to discuss this and ask for your opinion. I may join you for the meeting after the sprint.

**Comment by romulogoncalves** [comment]
@fdiblen are you aware that you will have to talk about this today at the Data-SIG session? Not sure if you are in the data-sig mailing list.

**Comment by fdiblen** [comment]
@romulogoncalves thanks for the reminder. Yes, I am in the mailing list.

**Comment by sverhoeven** [comment]
From the Hadoop ecosystem you have the [ORC](https://orc.apache.org/) and [Parquet](http://parquet.apache.org/) formats which can store dataframes. Would be nice to have support for these as well.

**Comment by sverhoeven** [comment]
https://wiki.postgresql.org/wiki/Foreign_data_wrappers can wrap most of the suggested formats in PostgreSQL

**Comment by c-martinez** [comment]
@fdiblen - can you fill a table with data formats & applicable projects ?

**Comment by romulogoncalves** [comment]
@fdiblen can we visualize graphs and linked data? Maybe another session about it with some use cases.

**Comment by c-martinez** [comment]
@fdiblen  -- This issue is quite old by now. I will close it, but please open it again if it is still necessary.

**Comment by fdiblen** [comment]
We had a few discussions in SIG meetings but I dont remember why we decided to keep this open.
