### ISSUE TITLE
Intro into datashader

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/ldm-sig#24]
Datashader turns even the largest datasets into images, faithfully preserving the data's distribution. http://datashader.org 

Create example notebooks showing of public datasets of projects.

**Comment by sverhoeven** [comment]
See https://github.com/NLeSC/data-sig/tree/datashader branch for progress

**Comment by fdiblen** [comment]
A similar tool called mapd: https://github.com/omnisci
A blog post: https://www.omnisci.com/blog/mapd-open-sources-gpu-powered-database/

**Comment by c-martinez** [comment]
@Tommos0, @bpmweel -- have a look at this, pretty cool stuff!

**Comment by romulogoncalves** [comment]
We just found out about http://kepler.gl/#/ from Maarten.

**Comment by c-martinez** [comment]
Merged #27 demo can be found under `data-sig/workshops/datashader/`
