### ISSUE TITLE
Scientific Symposium: FAIR Data Science for Green Life Sciences | 12 December 2018

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/ldm-sig#25]
Meer info over het Symposium vind je hier: https://www.wur.nl/en/activity/Scientific-Symposium-FAIR-Data-Science-for-Green-Life-Sciences.htm

Call for Abstracts: https://www.wur.nl/en/article/Abstract-Submission-Form-Scientific-Symposium-FAIR-Data-Science-for-Green-Life-Sciences.htm

**Comment by arnikz** [comment]
I'm planning to attend/submit an abstract together with the project partners ([candYgene](https://www.esciencecenter.nl/project/prediction-of-candidate-genes-for-traits-using-interoperable-genome-annotat)).

**Comment by romulogoncalves** [comment]
@arnikz that's great. We got an email from the DT about it and we would like to know who already submitted something and if we should encourage others to also submit an abstract.

Will you attend Data-SIG today? It would be great if you in a minute tell us what your abstract talks about.

**Comment by romulogoncalves** [comment]
@ridderl @arnikz it seems you are the ones that could go there and have one to two abstracts. If you have suggestions, let us know.

**Comment by romulogoncalves** [comment]
@ridderl  @sverhoeven is there a change to submit an abstract about the visualization tool for Genes?

**Comment by arnikz** [comment]
Submitted abstract about the [pbg-ld](https://www.research-software.nl/software/linked-data-platform-for-plant-breeding-genomics) platform.
