### ISSUE TITLE
Streaming processing

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/ldm-sig#26]
We should talk about what is going on in stream processing and who knows about it at NLeSC.

Some technologies:
* Kafka
* Apache Storm
* Apache Flink
* Apache Spark Stream

**Comment by romulogoncalves** [comment]
`Kafka is a data pipeline system with light stream processing`:

Kafka has light Stream processing which is possible with [Kafka streams](https://www.confluent.io/blog/introducing-kafka-streams-stream-processing-made-simple/) and [KSQL](https://www.confluent.io/blog/data-wrangling-apache-kafka-ksql). For data management Kafka streams uses RocksDB (developed and maintained by Facebook Database Engineering Team). It is a persistent key-value store.

[Kafka API](https://kafka.apache.org/documentation/#api) is simple and this blog explains in a nutshell how [Kafka architecture](https://data-flair.training/blogs/kafka-architecture/) looks like. ![image](https://user-images.githubusercontent.com/6976972/47492449-4ebeab00-d84d-11e8-9f29-46add173160e.png)

For complex stream processing the systems of choice are [Apache Storm](http://storm.apache.org/), [Apache Flink](https://flink.apache.org/) and [Apache Spark Streaming](https://spark.apache.org/streaming/).

**Comment by c-martinez** [comment]
@romulogoncalves -- you had some slides about this? Could we possibly link to them here?
