### ISSUE TITLE
Graph databases

### ISSUE THREAD

**Issue by fdiblen** [NLeSC/ldm-sig#28]
It would be nice to have discussion on Graph databases. If we have anyone with some experience, would be nice to invite for the discussion.

I guess @arnikz is also interested in the topic.

Topics to discuss:
 - in what cases we need graph databases
 - how can we use it 
 - what tools are available

**Comment by c-martinez** [comment]
Slides from @fdiblen are available [here](https://github.com/NLeSC/data-sig/blob/master/workshops/graphdb/Data_SIG_Graph_databases.pdf)
