### ISSUE TITLE
Data2Paper

### ISSUE THREAD

**Issue by jmaassen** [NLeSC/ldm-sig#29]
I ran into this at the Digital Infrastructures for Research (Di4R) conference: 

https://data2paper.org/

It's basically a web template that makes it easier to create data papers by importing as much meta info as possible from DOIs, ORCIDs, etc) but also from publishers. Still in beta, but may be interesting for us. 

Maybe good if the data sig has look at this?

**Comment by romulogoncalves** [comment]
@jmaassen as we talked, it would be nice to have you at up coming data-sig. It will this Thursday from 1PM to 2PM at the `Universal Turing Machine`.

**Comment by romulogoncalves** [comment]
@jmaassen it would be nice to have a comparison with Zenodo, what are the extra features and advantages compared to Zenodo?
