### ISSUE TITLE
Webinar: FAIR data in practice

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/ldm-sig#31]
Is anybody interested in attending this webinar?

#

We kindly invite you to the webinar “FAIR data in practice: From FAIRy tale to FAIR enough” on 11 December at 3 pm CET that DANS organises.
 
FAIR data, FAIRness, FAIR compliance: did you also stumble upon the capitalized version of “fair” often in the past couple of months? Did you sometimes wonder what this acronym means exactly in relation to your own work or for the research community in general? Or do you know about the FAIR principles in detail and would like to get to know more about some of the most recent discussions on that topic? Then the webinar 'FAIR data in practice: From FAIRy tale to FAIR enough' organized by DANS is for you.

# Webinar FAIR data in practice: From FAIRy tale to FAIR enough
The webinar will start with a short introduction on FAIR data, its status and use within the scientific community. The first part will consist of a presentation of the FAIR data checklist for researchers. This checklist is designed to support researchers with little experience in depositing and sharing their data digitally. The demonstration of the checklist during the webinar will show how the researcher is guided through questions that help assess the degree to which her or his data is deposited in a FAIR way.
The second part will be  a presentation on how trustworthy data repositories enable FAIR data, taking as an example the CoreTrustSeal Requirements. A mapping between CoreTrustSeal Requirements and the FAIR principles will reveal the synergies and complementarity to enable a FAIR data environment on the level of files, datasets, and repositories.
Last but not least, there will be time for a Q&A session.

Speakers: Peter Doorn, Ingrid Dillo, Eliane Fankhauser, Mustapha Mokrane.

More information and registration: https://dans.knaw.nl/en/current/news/webinar-fair-data-in-practice-from-fairy-tale-to-fair-enough?set_language=en

**Comment by romulogoncalves** [comment]
Interesting event, everyone was notified about it.
