### ISSUE TITLE
FAIR workflows

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/ldm-sig#33]
@ridderl brought this topic up: the FAIR workflows project incorporates aspects of FAIR data and workflows (and perhaps FAIR software). What aspects need to be considered?

@ridderl -- could you add some details on specific questions we should try to answer?

It would be nice if people from the workflows SIG could join as well :-)

**Comment by ridderl** [comment]
Question 1: how do the current ideas about FAIR workflows and FAIR software relate to each other.
For example: one objective in the FAIR workflows project is to describe the subsequent steps in a workflow semantically, as a so-called protocol, in such a way that the workflow can be re-run or even re-implemented on different platforms, or to facilitate replacement of software used in one specific step by another implementation. This latter objective I guess could be related to question of "Interoperability" of software.

**Comment by ridderl** [comment]
Question 2:
A FAIR workflow is supposed to more or less automatically produce FAIR data. Given our knowledge on FAIR data, what requirements can we define for the FAIR workflow platform to achieve this.

**Comment by rzinkstok** [comment]
Question 3: our PI has a strong preference for using nanopublications as the medium for publishing data, workflows and provenance data. From a workflow perspective, it makes sense to go along with the CWL developments, where research objects are used (see CWLProv, https://github.com/common-workflow-language/cwlprov/). What is your opinion?

**Comment by c-martinez** [comment]
We agreed on:
 - Trying CWLprov
 - @arnikz would like to try to include OpenRefine cleaning step as CWL tool & record what the cleaning steps were
 - First we should ask ourselves the question: what do you want to use the provenance trace for? There is not much point having very detailed granularity if it is not being used.

**Comment by c-martinez** [comment]
@ridderl -- This issue is quite old by now, and I think FAIR workflows project has evolved since this issue was created. I will close it, but please open it again if there is something you would like to share (for example lessons learned) with the SIG on this topic.
