### ISSUE TITLE
Following events outside NLeSC

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/ldm-sig#37]
For instance:
https://www.uu.nl/en/research/research-data-management
https://www.dtls.nl/community/meetings/programmers-meetings/
https://lcrdm.nl/

Are there any other lists we should keep an eye on?

**Comment by mkuzak** [comment]
Datastewards Interest group  [mailing list](https://lists.dtls.nl/mailman/listinfo/datastewards-interest) and regular face to face meetings, more information on [the website](https://www.dtls.nl/community/interest-groups/data-stewards-interest-group/).
