### ISSUE TITLE
Dask on Das

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/ldm-sig#38]
@bpmweel could you provide a little description? If possible, a more descriptive title.

**Comment by c-martinez** [comment]
@bpmweel -- would you like to discuss this issue on the next data sig meeting (this thursday?)

**Comment by bpmweel** [comment]
Hi Carlos,

I’m afraid this week is very busy and full for me, so I would like to maybe do it the meeting after next.

Cheers,
Berend

**Comment by c-martinez** [comment]
Sure, no problem.

**Comment by romulogoncalves** [comment]
@bpmweel what about try a join session between Workflow and Orchestration SIG and Data SIG for this topic? For sure there is interest from both crowds to know about Dask. We are also planning to use it for MARIN project and I will use it for the Phenology project.

Plus a cool pilot on how SIGs can collaborate.

**Comment by romulogoncalves** [comment]
I think the issue can be closed. A new issue should be opened either for a join session between both SIGs or a tutorial.
