### ISSUE TITLE
BigEarth Net: A New Large-Scale Sentinel-2 Benchmark Archive

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/ldm-sig#39]
During BiDS'19 I met the ones working on http://bigearth.net/. 

"The BigEarthNet is a new large-scale Sentinel-2 benchmark archive, consisting of 590,326 Sentinel-2 image patches. To construct the BigEarthNet, 125 Sentinel-2 tiles acquired between June 2017 and May 2018 over the 10 countries (Austria, Belgium, Finland, Ireland, Kosovo, Lithuania, Luxembourg, Portugal, Serbia, Switzerland) of Europe were initially selected. All the tiles were atmospherically corrected by the Sentinel-2 Level 2A product generation and formatting tool (sen2cor). Then, they were divided into 590,326 non-overlapping image patches. Each image patch was annotated by the multiple land-cover classes (i.e., multi-labels) that were provided from the CORINE Land Cover database of the year 2018 (CLC 2018)."

**Comment by c-martinez** [comment]
@romulogoncalves will forward to ML-SIG
