### ISSUE TITLE
Sensitive data handling

### ISSUE THREAD

**Issue by arnikz** [NLeSC/ldm-sig#44]
Discuss NLeSC projects that require a.o. data anonymization.

**Comment by eriktks** [comment]
Background information: At this moment I am collecting information about the usage of privacy-sensitive data in eScience projects (current, past and future) to find out what our best practices are in this area. I will present a summary of these findings at our data sig and at a national task group on data anonymization I joined recently:
https://www.edugroepen.nl/sites/RDM_platform/LCRDM/Wikipages/Taakgroep%20Anonimisering.aspx

I have sent the following questions to engineers involved in projects that might deal with privacy-sensitive data:

1. Did your project involve privacy-sensitive data like person names?
2. Answer only if the answer to question 1 was yes: Did our escience engineers have access to these privacy-sensitive data?
3. Answer only if the answer to question 2 was yes: Were the data preprocessed to remove privacy-sensitive information, for example by data anonymisation?
4. Answer only if the answer to question 3 was yes: How were the data processed to remove privacy-sensitive information?

If you think the answer to question one for any of your projects would be yes then I am interested in your experiences.

**Comment by jiskattema** [comment]
Hi Erik, good to see you working on this! Wrt. to the AVG (GDPR) we already did a similar inventory (looking only at point 1 and 2) some time ago; but projects probably have progressed (or new ones started) so good to repeat it.
Can you keep me informed of the outcome? In any case, engineers working with (possibly) personal identifiable data should come talk to our contact person for privacy (me at the moment).

**Comment by arnikz** [comment]
@jiskattema you are welcome to join and to share your experience and the "inventory" as well.

**Comment by c-martinez** [comment]
There is a [report](https://github.com/NLeSC/data-sig/blob/master/documents/nlesc-privacy.doc) from this issue -- thanks @eriktks !
