### ISSUE TITLE
 DataCubes for Earth Observation

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/ldm-sig#45]
In Astronomy we have already used DataCubes to store and query multi-dimensional data.
In Earth observation is becoming hot the discussion despite the concept is been there for a while. It got hot because of OpenDataCube.

I was at BiDS'19 and Living Planet Symposium and I heard a lot about OpenDataCube (https://www.opendatacube.org/).
At Living Planet Symposium I had the chance to talk with one of the major engineers.

I would like to know if any of you have used it or knows about it?
What about Rasdman? Have we used at NLeSC? Does anyone have experience with it. I am asking because I know well Peter Bauman, but I am not so fan of the non-open source approach of Rasdman.

**Comment by romulogoncalves** [comment]
@jiskattema has shared an interesting tool: Iris - "A powerful, format-agnostic, community-driven Python library for analysing and visualising Earth science data".

Latest documentation:
https://scitools.org.uk/iris/docs/latest/

gitHub:
https://github.com/SciTools/iris

**Comment by nielsdrost** [comment]
Hello, we use Iris in MAGIC. It is a core component of [ESMValTool](https://www.research-software.nl/software/esmvaltool). It in turn depends on dask (https://dask.org/), which also powers xarray (http://xarray.pydata.org/en/stable/)

Iris and xarray are also part of the pangeo community (https://pangeo.io/)

**Comment by arnikz** [comment]
In the recently granted project [RETURN](https://esciencecenter.nl/project/monitoring-tropical-forest-recovery-capacity-using-radar-sentinel-satellite), there is definitely an interest in this but don't know yet about the software experiences/preferences of our project partners.
