### ISSUE TITLE
Advice on H2020 Data Management Plan

### ISSUE THREAD

**Issue by Maartenvm** [NLeSC/ldm-sig#47]
We'd like to discuss the concept of our new DMP for the EU H2020 RECEIPT project. 

Questions include:
- What to do if licence information is unclear
 (https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210007101)

**Comment by arnikz** [comment]
Thanks @Maartenvm for your inquiry. Do you think you could prepare a "draft" of the DMP by next Thursday? We could go through the points that are unclear or difficult etc.

**Comment by Maartenvm** [comment]
Yes that's the intention

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by arnikz** [comment]
@Maartenvm: for usage/license/copyright-related info regarding the content of the Statistics Canada website see [here](https://www.statcan.gc.ca/eng/reference/copyright).

**Comment by c-martinez** [comment]
Thanks @Maartenvm -- we cannot link to the proposal here, but perhaps we can have a copy of the "final" version data-sig office group?
