### ISSUE TITLE
Datastewards Interest Group mailing list and f2f

### ISSUE THREAD

**Issue by mkuzak** [NLeSC/ldm-sig#48]
Hello,
Data Stewards Interest Group is both, a group of datastewards from around the Netherlands, meeting regularly in person, and a mailing list. The goals of the group align with the scope of this SIG. It would be great if one or more people join the mailing list and f2f meetings. We need to keep track of the developments in the datastewardship area at the national level and learn from other institutions. Next face to face meeting will take place in Utrecht, [Jaarbeurs Innovation Mile](https://jim.spaces.nexudus.com/en) on January 31.
[Data Stewards Interest Group mailing list](https://lists.dtls.nl/mailman/listinfo/datastewards-interest)
[Data Stewards Interest Group website](https://www.dtls.nl/community/interest-groups/data-stewards-interest-group/)

**Comment by c-martinez** [comment]
@mkuzak -- this is part of #37, so I will close this issue.
