### ISSUE TITLE
23 things research data

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/ldm-sig#52]
Since the 23 things project has now finished, perhaps it might be a good moment to have at the outcomes of the project and see where we can fit them in our center (for example, in the guide or the turing way).

@mkuzak -- would it be possible for you to discuss the 23 things in a data-sig session?

**Comment by mkuzak** [comment]
Yes, I think it's interesting. I don't know if I will be available. When would that be?

**Comment by c-martinez** [comment]
Next SIG meeting is 5 oct (i.e. later today) -- might be a bit short notice for it.

Otherwise, the next one is 2 nov -- would that work?

**Comment by mkuzak** [comment]
> Next SIG meeting is 5 oct (i.e. later today) -- might be a bit short notice for it.

it is. Unfortunately, it is not possible.

> Otherwise, the next one is 2 nov -- would that work?

no, I'm not available on Nov 2

**Comment by c-martinez** [comment]
The one after that is 30 Nov.

**Comment by mkuzak** [comment]
that could work

**Comment by c-martinez** [comment]
Good -- let's schedule you in for 30 Nov session :-)

**Comment by mkuzak** [comment]
please send me the calendar invite
how much time do I have?

**Comment by mkuzak** [comment]
I got the calendar invite, thank you. How much time do I have for the talk? Is there a meeting agenda?

**Comment by c-martinez** [comment]
You have as much time as you need -- at the moment this is the only topic in the agenda (unless other issues open up between now and the SIG meeting).

**Comment by mkuzak** [comment]
ok, I will take the first 15 minutes then. I will likely not going to stay for the whole meeting.

**Comment by mkuzak** [comment]
23 Research Data Things presented during Data SIG meeting on November 30, 2020. 

Resources in [the Document](https://nlesc.sharepoint.com/:w:/s/ldm/EfIZugi-W69Elx97yHyjlmoB69FuhqZK1_oWua9bcGbO2w?e=D76iTq)

**Comment by arnikz** [comment]
@mkuzak: could you add the link(s) to our guide in particular [this](https://guide.esciencecenter.nl/#/citable_software/publishing_results?id=publishing-scientific-results) chapter? Thanks.

**Comment by c-martinez** [comment]
I've opened an issue on the guide for this.

Thanks for your talk @mkuzak!
