### ISSUE TITLE
Nanopublications in scientific discourse

### ISSUE THREAD

**Issue by arnikz** [NLeSC/ldm-sig#55]
Intro to [nanopub](https://www.research-software.nl/software/nanopub) Python library and hands-on by @raar1.

**Comment by c-martinez** [comment]
Notebook for this session: https://github.com/fair-workflows/nanopub/blob/main/examples/DATA_SIG_handson_session.ipynb

Queries behind the nanopub server are:
https://github.com/peta-pico/nanopub-api

Swagger API behind the nanopub server here: http://grlc.io/api-git/peta-pico/nanopub-api
