### ISSUE TITLE
Point Clouds

### ISSUE THREAD

**Issue by AdamBelloum** [NLeSC/ldm-sig#63]
**Title**: Point Clouds
**Speaker**: Thijs van Lankveld
[**recording**](https://nlesc-my.sharepoint.com/:v:/g/personal/a_belloum_esciencecenter_nl/ET3owGJ87Q1KrjpJoWCpK4sB9dA1dpsYSJptDVcDUFjdkw?e=A9hxpv)
[**Slides**]()

**Comment by AdamBelloum** [comment]
During the Talk Thijs mention ICP and alignment, the following series of Video explain ICP in more Details

- ICP & Point Cloud Registration - Part 3: Non-linear Least Squares [part 1](https://www.youtube.com/watch?v=ktRqKxddjJk&list=RDCMUCi1TC2fLRvgBQNe-T4dp8Eg&index=3)
- know data association [part 2](https://www.youtube.com/watch?v=ktRqKxddjJk&list=RDCMUCi1TC2fLRvgBQNe-T4dp8Eg&index=3) 
- we don’t know data association [part 3](https://www.youtube.com/watch?v=CJE59i8oxIE)

**Comment by c-martinez** [comment]
@AdamBelloum -- the link to the slides seems to be broken (or rather it points back to this issue)
